#!/usr/bin/env python3

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

# Example usage
if __name__ == "__main__":
    for i in range(1000):  # Change 11 to calculate more Fibonacci numbers
        print(fibonacci(28))
